#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Oct 02 14:39:23 CEST 2019
# SW Build 2035080 on Fri Oct 20 14:20:00 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvhdl --incr --relax -prj tb_AXI4Stream_OverflowCounter_vhdl.prj"
ExecStep xvhdl --incr --relax -prj tb_AXI4Stream_OverflowCounter_vhdl.prj 2>&1 | tee -a compile.log
