#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 02 15:21:37 CEST 2019
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_AXI4Stream_OverflowCounter_behav -key {Behavioral:sim_1:Functional:tb_AXI4Stream_OverflowCounter} -tclbatch tb_AXI4Stream_OverflowCounter.tcl -view /home/nicola/Documents/Vivado/Projects/Time-to-Digital Converter/OverflowCounter/OverflowCounter.srcs/sim_1/imports/new/tb_AXI4Stream_OverflowCounter_behav.wcfg -log simulate.log
